[package]
name = "papyurus-compiler-cli"
version = "0.1.0"
edition = "2021"

[dependencies.papyrus-lexer]
path = "../lexer"

[dependencies]
anyhow = "1.0.57"
clap = { version = "3.1.18", features = ["derive"] }