[package]
name = "papyrus_compiler_cli"
version = "0.1.0"
edition = "2021"

[dependencies.papyrus_compiler_lexer]
path = "../lexer"

[dependencies]
anyhow = "1.0.57"
clap = { version = "3.1.18", features = ["derive"] }