[package]
name = "papyrus_compiler_core"
version = "0.1.0"
edition = "2021"

[dependencies.papyrus_compiler_lexer]
path = "../lexer"

[dependencies.papyrus_compiler_parser]
path = "../parser"

[dependencies]
anyhow = "1.0.57"
ariadne = "0.1.5"