name: mdBook Deployment

on:
  push:
    branches: [ master ]
    paths:
      - 'docs/**'

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

    - name: Install mdBook
      run: |
        mkdir mdBook
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.18/mdbook-v0.4.18-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdBook
        echo `pwd`/mdBook >> $GITHUB_PATH

    - name: Build
      run: mdbook build docs

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: docs/book