name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - '**.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy

    - name: Cache cargo dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
        key: cargo-deps-${{ hashFiles('**/Cargo.lock') }}

    - name: Run clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features --locked

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true

    - name: Cache cargo dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
        key: cargo-deps-${{ hashFiles('**/Cargo.lock') }}

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --features test-external-scripts --locked

    - name: Run heap profiling
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --locked --features dhat-heap --features test-external-scripts --package papyrus_compiler_parser --lib tests::heap_profiling -- --exact